// Player Ship --
export const GAMELOOP_PLAYER_SHIP_UPDATE = 'GAMELOOP_PLAYER_SHIP_UPDATE'
export const UPDATE_HULL = 'UPDATE_HULL'
export const UPDATE_SHIELDS = 'UPDATE_SHIELDS'
export const UPDATE_ENERGY = 'UPDATE_ENERGY'
export const UPDATE_SPEED = 'UPDATE_SPEED'
export const UPDATE_ROTATION = 'UPDATE_ROTATION'
export const UPDATE_FUEL = 'UPDATE_FUEL'
export const SET_PILOT_MODE = 'SET_PILOT_MODE'
export const SET_IS_THRUSTING = 'SET_IS_THRUSTING'
export const SET_IS_BRAKING = 'SET_IS_BRAKING'
export const SET_IS_LATERAL_THRUSTING_LEFT = 'SET_IS_LATERAL_THRUSTING_LEFT'
export const SET_IS_LATERAL_THRUSTING_RIGHT = 'SET_IS_LATERAL_THRUSTING_RIGHT'
export const SET_IS_FIRING_WEAPON = 'SET_IS_FIRING_WEAPON'

// Logs --
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
